# Generated by Django 5.0.1 on 2024-01-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('genre', models.CharField(max_length=200)),
                ('rank', models.IntegerField(choices=[(1, 'Bad'), (2, 'Not_Bad'), (3, 'So_so'), (4, 'Good'), (5, 'Perfect')])),
                ('running_time', models.TimeField()),
                ('content', models.TextField()),
                ('director', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=200)),
            ],
        ),
    ]
